config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  match 'tests', to: 'home#index', via: :post
end

app/models/algorithm.rb
class Algorithm < ApplicationRecord
  scope :ordered, -> { order(title: :asc) }
  has_many :tests
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :algorithm
  scope :by_category, -> (category) { where(category: category) }
  scope :timed, -> { where.not(end_time: nil) }

  validates :start_time, presence: true

  def execution_time
    end_time - start_time
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :run_test, only: :index
  
  def index
    @algorithms = Algorithm.ordered
  end

  private

  def run_test
    return if params[:algorithm].nil?

    algorithm = Algorithm.find(params[:algorithm])
    Test::Run.new.call(algorithm, params[:sort_by])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def average_execution_time(algo, category)
    time = 'no tests'
    time = algo.tests.timed.by_category(category).map(&:execution_time).sum / algo.tests.timed.by_category(category).count if algo.tests.timed.by_category(category).count.positive?
    time
  end

  def mean_execution_time(algo, category)
    time = 'no tests'
    time = median(algo.tests.timed.by_category(category).map(&:execution_time)) if algo.tests.timed.by_category(category).count.positive?
    time
  end

  # found via https://stackoverflow.com/questions/14859120/calculating-median-in-ruby
  def median(array)
    sorted = array.sort
    len = sorted.length
    (sorted[(len - 1) / 2] + sorted[len / 2]) / 2.0
  end
end

app/views/home/index.html.slim
.container
  .row
    .eight.columns
      h4 Sort by String
      table.u-full-width
        thead
          tr
            th Algorithm
            th # of Tests
            th Average Execution Time
            th Mean Execution Time
        tbody
          - @algorithms.each do |algo|
            - unless algo.title == 'Run All'
              tr
                td #{algo.title}
                td #{algo.tests.timed.by_category('name').count}
                td #{average_execution_time(algo, 'name')}
                td #{mean_execution_time(algo, 'name')}

    .four.columns
      = form_tag tests_path do
        = hidden_field_tag :sort_by ,'name'
        label for='algorithms' Select Algorithm
        = select_tag :algorithm, options_from_collection_for_select(Algorithm.ordered, 'id', 'title')
        br
        = submit_tag 'run tests', class: 'button-primary'
  .row.margin-40
    .eight.columns
      h4 Sort by Int
      table.u-full-width
        thead
          tr
            th Algorithm
            th # of Tests
            th Average Execution Time
            th Mean Execution Time
        tbody
          - @algorithms.each do |algo|
            - unless algo.title == 'Run All'
              tr
                td #{algo.title}
                td #{algo.tests.timed.by_category('number').count}
                td #{average_execution_time(algo, 'number')}
                td #{mean_execution_time(algo, 'number')}

    .four.columns
      = form_tag tests_path do
        = hidden_field_tag :sort_by, 'number'
        label for='algorithms' Select Algorithm
        = select_tag :algorithm, options_from_collection_for_select(Algorithm.ordered, 'id', 'title')
        br
        = submit_tag 'run tests', class: 'button-primary'
    

app/views/layouts/application.html.slim
doctype html
html
  head
    title Architecture Benchmarks
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield